var nameList = [
  "Aarav",
  "Vivaan",
  "Aditya",
  "Dev",
  "Arjun",
  "Sai",
  "Krishna",
  "Aryan",
  "Vihaan",
  "Kabir",
  "Reyansh",
  "Ayaan",
  "Dhruv",
  "Ishaan",
  "Rudra",
  "Atharv",
  "Ansh",
  "Parth",
  "Aarush",
  "Rishi",
  "Kian",
  "Kunal",
  "Rohan",
  "Vir",
  "Yash",
  "Raghav",
  "Samar",
  "Neil",
  "Arnav",
  "Vivaan",
  "Manav",
  "Nishant",
  "Arin",
  "Shiv",
  "Aniket",
  "Om",
  "Pranav",
  "Tanish",
  "Darsh",
  "Laksh",
  "Shivansh",
  "Vivan",
  "Ved",
  "Reyan",
  "Harsh",
  "Nirvaan",
  "Armaan",
  "Aaditya",
  "Siddharth",
  "Ayush",
  "Shaurya",
  "Krish",
  "Arav",
  "Vihaan",
  "Atharva",
  "Aarav",
  "Ishan",
  "Yuvraj",
  "Hriday",
  "Anirudh",
  "Devansh",
  "Ritvik",
  "Harshil",
  "Shaan",
  "Hrithik",
  "Kartik",
  "Sarthak",
  "Ayaan",
  "Ivaan",
  "Vihaan",
  "Avyaan",
  "Nivaan",
  "Aryav",
  "Advay",
  "Jivaan",
  "Lakshya",
  "Rishabh",
  "Aaryan",
  "Aaditya",
  "Aayush",
  "Aarush",
  "Abeer",
  "Aahan",
  "Aarav",
  "Agastya",
  "Ahaan",
  "Ahil",
  "Ahaan",
  "Ahil",
  "Ajay",
  "Akash",
  "Akhil",
  "Aman",
  "Amay",
  "Amogh",
  "Anay",
  "Angad",
  "Anirban",
  "Anish",
  "Ankit",
  "Anshul",
  "Anuj",
  "Anup",
  "Arhaan",
  "Arjit",
  "Arjun",
  "Arman",
  "Arnav",
  "Arun",
  "Ashish",
  "Ashwin",
  "Avi",
  "Avinash",
  "Bharat",
  "Bhavin",
  "Bhuvan",
  "Chaitanya",
  "Chetan",
  "Darsh",
  "Dhanush",
  "Dhaval",
  "Dhruv",
  "Divyansh",
  "Eklavya",
  "Ekansh",
  "Gaurav",
  "Gautam",
  "Girish",
  "Haaris",
  "Hardik",
  "Harish",
  "Harsh",
  "Himansh",
  "Hriday",
  "Ishan",
  "Ishwar",
  "Jatin",
  "Jay",
  "Jeevan",
  "Jignesh",
  "Kabir",
  "Kailash",
  "Kamal",
  "Karan",
  "Kartik",
  "Kaushal",
  "Keshav",
  "Kiaan",
  "Kishan",
  "Krish",
  "Krishna",
  "Kuldeep",
  "Lakshay",
  "Lalit",
  "Lav",
  "Lokesh",
  "Madhav",
  "Mahesh",
  "Manan",
  "Manav",
  "Mihir",
  "Mitul",
  "Mohan",
  "Mukul",
  "Naitik",
  "Naksh",
  "Naman",
  "Nirav",
  "Nishant",
  "Om",
  "Omkar",
  "Parth",
  "Piyush",
  "Pranav",
  "Pranit",
  "Pratyush",
  "Pravin",
  "Preet",
  "Rachit",
  "Raghav",
  "Rahul",
  "Raj",
  "Rakesh",
  "Raman",
  "Ramesh",
  "Rishi",
  "Rishit",
  "Ritvik",
  "Rohan",
  "Rudra",
  "Sahil",
  "Samar",
  "Samarth",
  "Sandeep",
  "Sanjay",
  "Sarang",
  "Sarvesh",
  "Satyam",
  "Shaan",
  "Shiv",
  "Shivansh",
  "Shlok",
  "Shrey",
  "Siddharth",
  "Somesh",
  "Sparsh",
  "Sumit",
  "Surya",
  "Tarun",
  "Tushar",
  "Ujjwal",
  "Utkarsh",
  "Vedant",
  "Veer",
  "Vihaan",
  "Vikram",
  "Vinay",
  "Vineet",
  "Vishal",
  "Vivan",
  "Yash",
  "Yug",
  "Zayan",
  "Zeeshan",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

export function makeRandomMessage() {
  const messages = [
    "Hey everyone! How's it going?",
    "This video is amazing!",
    "I love this content!",
    "Can someone explain this part?",
    "Wow, this is so cool!",
    "What's your favorite part of the video?",
    "I'm learning so much from this channel.",
    "Keep up the great work!",
    "Who else is watching this?",
    "This is my favorite YouTuber!",
    "Great video! Can't wait for the next one.",
    "Hello from Solapur!",
    "Hello from Delhi!",
    "Hello from Mumbai!",
    "Hello from Pune!",
    "Hello from Hydrabad!",
    "Hello from Bengaluru!",
    "Anyone else here for the first time?",
    "This video just made my day!",
    "Thanks for the awesome content!",
    "Amazing production quality!",
    "The editing is top-notch!",
    "Love the creativity in this video!",
    "This is so informative!",
    "I'm definitely subscribing!",
    "What a fantastic video!",
    "I can't stop watching this channel!",
    "This is exactly what I needed!",
    "You always make great content!",
    "I wish I had discovered this channel sooner!",
    "This is my go-to channel for [Topic] content.",
    "Absolutely loving this!",
    "Who else agrees this is the best?",
    "I always learn something new here.",
    "Such high-quality videos!",
    "I can't wait to see what you post next.",
    "You deserve more subscribers!",
    "This video is pure gold!",
    "Your content never disappoints!",
    "This channel is a hidden gem.",
    "So glad I found this channel!",
    "You always exceed my expectations.",
    "This is my new favorite channel.",
    "Keep the great content coming!",
    "You're doing an amazing job!",
    "So many great tips in this video!",
    "I can't get enough of your videos.",
    "Thank you for sharing this!",
    "This is so helpful!",
    "Your videos are always so well-made.",
    "I'm learning so much from you.",
    "I appreciate all the effort you put into these videos.",
    "This is exactly what I was looking for.",
    "You have a new fan!",
    "This video is a game changer!",
    "I'm binge-watching your channel right now.",
    "Your content is always so engaging.",
    "This is so entertaining!",
    "I've learned so much from this channel.",
    "This is the best video I've seen all week!",
    "You're my favorite YouTuber!",
    "I always look forward to your videos.",
    "This video just made my day!",
    "You're so talented!",
    "I can't wait to try this myself.",
    "This is such a cool idea!",
    "I'm totally hooked on your channel.",
    "I love the way you explain things.",
    "Your videos are always so inspiring.",
    "This is going straight to my favorites.",
    "I'm so glad I clicked on this video.",
    "This is incredibly useful information.",
    "I can't wait to see more from you.",
    "This is exactly the content I love.",
    "You make everything look so easy!",
    "I always trust your recommendations.",
    "This is so well explained!",
    "Your channel is a treasure trove of knowledge.",
    "I'm so impressed with your work.",
    "This is exactly what I needed to see today.",
    "I'm going to share this with all my friends.",
    "You're a fantastic teacher.",
    "This video is a must-watch!",
    "I'm blown away by your creativity.",
    "This is such a helpful guide.",
    "You always make the best videos.",
    "I can't thank you enough for this video.",
    "I'm learning so much from your channel.",
    "This is the best content on YouTube!",
    "I'm so happy I found your channel.",
    "You have such a unique style.",
    "This video is so well-done!",
    "I'm always excited to see your new videos.",
    "You have an amazing talent.",
    "This is exactly what I've been looking for.",
    "You make learning so much fun!",
    "This is such a great tutorial.",
    "I love how detailed your videos are.",
    "This video is a lifesaver!",
    "You're so good at what you do.",
    "I can't get enough of your content.",
    "This is such a fantastic video.",
    "You always deliver the best content.",
    "This is my favorite video so far.",
    "I love your enthusiasm.",
    "This channel is a goldmine.",
    "You're an inspiration to us all.",
    "This video is pure genius!",
  ];

  const randomIndex = Math.floor(Math.random() * messages.length);
  return messages[randomIndex];
}

// export function makeRandomMessage(length) {
//   let result = "";
//   const characters =
//     "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
//   const charactersLength = characters.length;
//   let counter = 0;
//   while (counter < length) {
//     result += characters.charAt(Math.floor(Math.random() * charactersLength));
//     counter += 1;
//   }
//   return result;
// }
